
---------- TEST.BAT

---------- T
call loadScript j2s\org\jmol\awtjs\JmolURLConnection.js
call loadScript j2s\org\apache\harmony\luni\util\Msg.z.js
call loadScript j2s\org\jmol\awtjs2d\JmolURLConnection.js
call loadScript j2s\org\jmol\appletjs\Jmol.js
call loadScript j2s\org\jmol\api\JmolStatusListener.js
call loadScript j2s\org\jmol\api\JmolSyncInterface.js
call loadScript j2s\org\jmol\api\JmolCallbackListener.js
call loadScript j2s\org\jmol\appletjs\JmolAppletRegistry.js
call loadScript j2s\org\jmol\constant\EnumCallback.js
call loadScript j2s\org\jmol\i18n\GT.js
call loadScript j2s\org\jmol\util\Escape.js
call loadScript j2s\org\jmol\util\Logger.js
call loadScript j2s\org\jmol\util\Parser.js
call loadScript j2s\org\jmol\util\TextFormat.js
call loadScript j2s\org\jmol\util\StringXBuilder.js
call loadScript j2s\org\jmol\util\DefaultLogger.js
call loadScript j2s\org\jmol\util\ArrayUtil.js
call loadScript j2s\org\jmol\script\ScriptVariable.js
call loadScript j2s\org\jmol\util\LoggerInterface.js
call loadScript j2s\org\jmol\util\BitSetUtil.js
call loadScript j2s\org\jmol\script\Token.js
call loadScript j2s\org\jmol\util\Point3f.js
call loadScript j2s\org\jmol\modelset\Bond.js
call loadScript j2s\org\jmol\util\BitSet.js
call loadScript j2s\org\jmol\util\Tuple3f.js
call loadScript j2s\org\jmol\util\JmolEdge.js
call loadScript j2s\org\jmol\viewer\JmolConstants.js
call loadScript j2s\org\jmol\util\Colix.js
call loadScript j2s\org\jmol\util\Measure.js
call loadScript j2s\org\jmol\util\Elements.js
call loadScript j2s\org\jmol\util\Vector3f.js
call loadScript j2s\org\jmol\util\Int2IntHash.js
call loadScript j2s\org\jmol\constant\EnumPalette.js
call loadScript j2s\org\jmol\util\ColorUtil.js
call loadScript j2s\org\jmol\util\Shader.js
call loadScript j2s\org\jmol\util\Eigen.js
call loadScript j2s\org\jmol\util\Point4f.js
call loadScript j2s\org\jmol\util\Quaternion.js
call loadScript j2s\org\jmol\util\Matrix3f.js
call loadScript j2s\org\jmol\util\Quadric.js
call loadScript j2s\org\jmol\util\Tuple4f.js
call loadScript j2s\org\jmol\util\AxisAngle4f.js
call loadScript j2s\org\jmol\util\Matrix4f.js
call loadScript j2s\org\jmol\viewer\Viewer.js
call loadScript j2s\org\jmol\api\JmolViewer.js
call loadScript j2s\org\jmol\atomdata\AtomDataServer.js
call loadScript j2s\org\jmol\atomdata\RadiusData.js
call loadScript j2s\org\jmol\util\CommandHistory.js
call loadScript j2s\org\jmol\util\Dimension.js
call loadScript j2s\org\jmol\constant\EnumVdw.js
call loadScript j2s\org\jmol\adapter\smarter\SmarterJmolAdapter.js
call loadScript j2s\org\jmol\api\JmolAdapter.js
call loadScript j2s\org\jmol\constant\EnumQuantumShell.js
call loadScript j2s\org\jmol\modelset\Group.js
call loadScript j2s\org\jmol\adapter\smarter\AtomIterator.js
call loadScript j2s\org\jmol\adapter\smarter\AtomSetCollection.js
call loadScript j2s\org\jmol\constant\EnumStructure.js
call loadScript j2s\org\jmol\api\JmolAdapterAtomIterator.js
call loadScript j2s\org\jmol\adapter\smarter\Atom.js
call loadScript j2s\org\jmol\adapter\smarter\Bond.js
call loadScript j2s\org\jmol\api\Interface.js
call loadScript j2s\org\jmol\util\Point3i.js
call loadScript j2s\org\jmol\adapter\smarter\BondIterator.js
call loadScript j2s\org\jmol\adapter\smarter\AtomSetObject.js
call loadScript j2s\org\jmol\adapter\smarter\Resolver.js
call loadScript j2s\org\jmol\util\Tuple3i.js
call loadScript j2s\org\jmol\api\JmolAdapterBondIterator.js
call loadScript j2s\org\jmol\adapter\smarter\StructureIterator.js
call loadScript j2s\org\jmol\adapter\smarter\AtomSetCollectionReader.js
call loadScript j2s\org\jmol\util\LimitedLineReader.js
call loadScript j2s\org\jmol\api\JmolAdapterStructureIterator.js
call loadScript j2s\org\jmol\util\CompoundDocument.js
call loadScript j2s\org\jmol\util\ZipUtil.js
call loadScript j2s\org\jmol\constant\EnumAxesMode.js
call loadScript j2s\org\jmol\constant\EnumFileStatus.js
call loadScript j2s\org\jmol\util\BinaryDocument.js
call loadScript j2s\org\jmol\util\ZipData.js
call loadScript j2s\org\jmol\constant\EnumStereoMode.js
call loadScript j2s\org\jmol\script\ScriptCompiler.js
call loadScript j2s\org\jmol\script\ScriptCompilationTokenParser.js
call loadScript j2s\org\jmol\script\ScriptEvaluator.js
call loadScript j2s\org\jmol\constant\EnumAnimationMode.js
call loadScript j2s\org\jmol\modelset\Atom.js
call loadScript j2s\org\jmol\util\JmolNode.js
call loadScript j2s\org\jmol\util\Point3fi.js
call loadScript j2s\org\jmol\modelset\AtomCollection.js
call loadScript j2s\org\jmol\geodesic\EnvelopeCalculation.js
call loadScript j2s\org\jmol\modelset\LabelToken.js
call loadScript j2s\org\jmol\atomdata\AtomData.js
call loadScript j2s\org\jmol\util\Geodesic.js
call loadScript j2s\org\jmol\util\Normix.js
call loadScript j2s\org\jmol\modelset\MeasurementData.js
call loadScript j2s\org\jmol\modelset\ModelCollection.js
call loadScript j2s\org\jmol\modelset\TickInfo.js
call loadScript j2s\org\jmol\api\JmolMeasurementClient.js
call loadScript j2s\org\jmol\modelset\Measurement.js
call loadScript j2s\org\jmol\modelset\BondCollection.js
call loadScript j2s\org\jmol\util\BoxInfo.js
call loadScript j2s\org\jmol\modelset\BondIteratorSelected.js
call loadScript j2s\org\jmol\modelset\HBond.js
call loadScript j2s\org\jmol\modelset\BondIterator.js
call loadScript j2s\org\jmol\util\TriangleData.js
call loadScript j2s\org\jmol\bspt\Bspf.js
call loadScript j2s\org\jmol\modelset\AtomIteratorWithinModel.js
call loadScript j2s\org\jmol\bspt\Bspt.js
call loadScript j2s\org\jmol\api\AtomIndexIterator.js
call loadScript j2s\org\jmol\bspt\CubeIterator.js
call loadScript j2s\org\jmol\bspt\Leaf.js
call loadScript j2s\org\jmol\modelset\AtomIteratorWithinModelSet.js
call loadScript j2s\org\jmol\bspt\Element.js
call loadScript j2s\org\jmol\bspt\Node.js
call loadScript j2s\org\jmol\util\JmolMolecule.js
call loadScript j2s\org\jmol\util\OutputStringBuilder.js
call loadScript j2s\org\jmol\util\XmlUtil.js
call loadScript j2s\org\jmol\script\ScriptContext.js
call loadScript j2s\org\jmol\script\ScriptMathProcessor.js
call loadScript j2s\org\jmol\script\ScriptVariableInt.js
call loadScript j2s\org\jmol\util\ColorEncoder.js
call loadScript j2s\org\jmol\viewer\PropertyManager.js
call loadScript j2s\org\jmol\shape\Object2d.js
call loadScript j2s\org\jmol\util\GData.js
call loadScript j2s\org\jmol\api\JmolGraphicsInterface.js
call loadScript j2s\org\jmol\util\JmolFont.js
call loadScript j2s\org\jmol\util\MeshSurface.js
call loadScript j2s\org\jmol\viewer\ActionManager.js
call loadScript j2s\org\jmol\viewer\FileManager.js
call loadScript j2s\org\jmol\viewer\StateManager.js
call loadScript j2s\org\jmol\script\ContextToken.js
call loadScript j2s\org\jmol\util\Rectangle.js
call loadScript j2s\org\jmol\viewer\MouseState.js
call loadScript j2s\org\jmol\modelset\MeasurementPending.js
call loadScript j2s\org\jmol\thread\HoverWatcherThread.js
call loadScript j2s\org\jmol\viewer\binding\Binding.js
call loadScript j2s\org\jmol\viewer\binding\DragBinding.js
call loadScript j2s\org\jmol\viewer\binding\JmolBinding.js
call loadScript j2s\org\jmol\thread\JmolThread.js
call loadScript j2s\org\jmol\viewer\binding\PfaatBinding.js
call loadScript j2s\org\jmol\viewer\binding\RasmolBinding.js
call loadScript j2s\org\jmol\api\JmolFilesReaderInterface.js
call loadScript j2s\org\jmol\util\Base64.js
call loadScript j2s\org\jmol\viewer\DataManager.js
call loadScript j2s\org\jmol\script\ScriptFlowContext.js
call loadScript j2s\org\jmol\script\ScriptFunction.js
call loadScript j2s\org\jmol\thread\ScriptParallelProcessor.js
call loadScript j2s\org\jmol\script\ScriptProcess.js
call loadScript j2s\org\jmol\thread\ScriptProcessRunnable.js
call loadScript j2s\org\jmol\viewer\ShapeManager.js
call loadScript j2s\org\jmol\shape\Shape.js
call loadScript j2s\org\jmol\thread\TimeoutThread.js
call loadScript j2s\org\jmol\util\CifDataReader.js
call loadScript j2s\org\jmol\util\SurfaceFileTyper.js
call loadScript j2s\org\jmol\util\TempArray.js
call loadScript j2s\org\jmol\viewer\AnimationManager.js
call loadScript j2s\org\jmol\viewer\ColorManager.js
call loadScript j2s\org\jmol\viewer\ModelManager.js
call loadScript j2s\org\jmol\viewer\ScriptManager.js
call loadScript j2s\org\jmol\thread\AnimationThread.js
call loadScript j2s\org\jmol\viewer\SelectionManager.js
call loadScript j2s\org\jmol\modelset\ModelLoader.js
call loadScript j2s\org\jmol\thread\CommandWatcherThread.js
call loadScript j2s\org\jmol\thread\ScriptQueueThread.js
call loadScript j2s\org\jmol\viewer\StatusManager.js
call loadScript j2s\org\jmol\modelset\Chain.js
call loadScript j2s\org\jmol\modelset\Model.js
call loadScript j2s\org\jmol\modelset\ModelSet.js
call loadScript j2s\org\jmol\viewer\TransformManager10.js
call loadScript j2s\org\jmol\viewer\TransformManager11.js
call loadScript j2s\org\jmol\viewer\TransformManager.js
call loadScript j2s\org\jmol\util\Hermite.js
call loadScript j2s\org\jmol\thread\MotionThread.js
call loadScript j2s\org\jmol\thread\SpinThread.js
call loadScript j2s\org\jmol\thread\VibrationThread.js
call loadScript j2s\org\jmol\awtjs2d\Platform.js
call loadScript j2s\org\jmol\api\ApiPlatform.js
call loadScript j2s\org\jmol\awtjs2d\AjaxURLStreamHandlerFactory.js
call loadScript j2s\org\jmol\awtjs2d\AjaxURLStreamHandler.js
call loadScript j2s\org\jmol\awtjs2d\Display.js
call loadScript j2s\org\jmol\awtjs2d\Font.js
call loadScript j2s\org\jmol\awtjs2d\Image.js
call loadScript j2s\org\jmol\awtjs2d\JmolFile.js
call loadScript j2s\org\jmol\api\JmolFileInterface.js
call loadScript j2s\org\jmol\awtjs2d\JmolFileAdapter.js
call loadScript j2s\org\jmol\api\JmolFileAdapterInterface.js
call loadScript j2s\org\jmol\awtjs2d\Mouse.js
call loadScript j2s\org\jmol\api\JmolMouseInterface.js
call loadScript j2s\org\jmol\api\Event.js
call loadScript j2s\org\jmol\g3d\Graphics3D.js
call loadScript j2s\org\jmol\api\JmolRendererInterface.js
call loadScript j2s\org\jmol\g3d\CircleRenderer.js
call loadScript j2s\org\jmol\g3d\CylinderRenderer.js
call loadScript j2s\org\jmol\g3d\HermiteRenderer.js
call loadScript j2s\org\jmol\g3d\ImageRenderer.js
call loadScript j2s\org\jmol\g3d\LineRenderer.js
call loadScript j2s\org\jmol\g3d\Pixelator.js
call loadScript j2s\org\jmol\g3d\PixelatorShaded.js
call loadScript j2s\org\jmol\g3d\Platform3D.js
call loadScript j2s\org\jmol\g3d\SphereRenderer.js
call loadScript j2s\org\jmol\g3d\TextRenderer.js
call loadScript j2s\org\jmol\g3d\TextSorter.js
call loadScript j2s\org\jmol\g3d\TextString.js
call loadScript j2s\org\jmol\g3d\TriangleRenderer.js
call loadScript j2s\org\jmol\util\Rgb16.js
call loadScript j2s\org\jmol\render\RepaintManager.js
call loadScript j2s\org\jmol\api\JmolRepaintInterface.js
call loadScript j2s\org\jmol\shape\Balls.js
call loadScript j2s\org\jmol\shape\AtomShape.js
call loadScript j2s\org\jmol\shape\Sticks.js
call loadScript j2s\org\jmol\shape\Measures.js
call loadScript j2s\org\jmol\shape\FontLineShape.js
call loadScript j2s\org\jmol\shape\FontShape.js
call loadScript j2s\org\jmol\shape\Bbcage.js
call loadScript j2s\org\jmol\shape\Uccage.js
call loadScript j2s\org\jmol\shape\Frank.js
call loadScript j2s\org\jmol\adapter\readers\molxyz\MolReader.js
call loadScript j2s\org\jmol\render\BallsRenderer.js
call loadScript j2s\org\jmol\render\ShapeRenderer.js
call loadScript j2s\org\jmol\render\SticksRenderer.js
call loadScript j2s\org\jmol\render\MeasuresRenderer.js
call loadScript j2s\org\jmol\render\FontLineShapeRenderer.js
call loadScript j2s\org\jmol\render\BbcageRenderer.js
call loadScript j2s\org\jmol\render\CageRenderer.js
call loadScript j2s\org\jmol\render\UccageRenderer.js
call loadScript j2s\org\jmol\util\SimpleUnitCell.js
call loadScript j2s\org\jmol\render\FrankRenderer.js
