
---------- TEST.BAT
call loadScript j2s\java\package.js
call loadScript j2s\java\package.js
call loadScript j2s\java\core.z.js
call loadScript j2s\java\lang\StringBuffer.js
call loadScript j2s\java\util\Hashtable.js
call loadScript j2s\java\net\URLConnection.js
call loadScript j2s\java\lang\StringBuilder.z.js
call loadScript j2s\java\util\Dictionary.js
call loadScript j2s\java\util\MapEntry.js
call loadScript j2s\java\util\AbstractCollection.js
call loadScript j2s\java\util\AbstractSet.js
call loadScript j2s\java\net\UnknownServiceException.js
call loadScript j2s\java\util\ArrayList.js
call loadScript j2s\java\util\Arrays.js
call loadScript j2s\java\util\Collections.js
call loadScript j2s\java\util\AbstractList.js
call loadScript j2s\java\util\Locale.js
call loadScript j2s\java\util\ResourceBundle.js
call loadScript j2s\java\util\AbstractMap.js
call loadScript j2s\java\util\SortedMap.js
call loadScript j2s\java\util\SortedSet.js
call loadScript j2s\java\util\Random.js
call loadScript j2s\java\net\UnknownServiceException.js
call loadScript j2s\java\lang\Enum.js
call loadScript j2s\java\text\MessageFormat.js
call loadScript j2s\java\lang\Runtime.js
call loadScript j2s\java\security\AccessController.js
call loadScript j2s\java\security\PrivilegedExceptionAction.js
call loadScript j2s\java\io\BufferedInputStream.js
call loadScript j2s\java\util\Properties.js
call loadScript j2s\java\io\FilterInputStream.js
call loadScript j2s\java\io\InputStream.js
call loadScript j2s\java\lang\Runtime.js
call loadScript j2s\java\security\AccessController.js
call loadScript j2s\java\security\PrivilegedExceptionAction.js
call loadScript j2s\java\io\BufferedOutputStream.js
call loadScript j2s\java\io\BufferedReader.js
call loadScript j2s\java\io\BufferedWriter.js
call loadScript j2s\java\io\FilterOutputStream.js
call loadScript j2s\java\io\Reader.js
call loadScript j2s\java\io\Writer.js
call loadScript j2s\java\io\OutputStream.js
call loadScript j2s\java\lang\Readable.js
call loadScript j2s\java\io\File.js
call loadScript j2s\java\io\FileWriter.js
call loadScript j2s\java\io\StringReader.js
call loadScript j2s\java\lang\Thread.js
call loadScript j2s\java\lang\ThreadGroup.js
call loadScript j2s\java\io\ByteArrayInputStream.js
call loadScript j2s\java\lang\Short.js
call loadScript j2s\java\io\File.js
call loadScript j2s\java\util\StringTokenizer.js
call loadScript j2s\java\io\FileWriter.js
call loadScript j2s\java\io\DataInputStream.js
call loadScript j2s\java\util\zip\GZIPInputStream.js
call loadScript j2s\java\util\zip\ZipInputStream.js
call loadScript j2s\java\io\DataInputStream.js
call loadScript j2s\java\util\Calendar.js
call loadScript j2s\java\util\zip\GZIPInputStream.js
call loadScript j2s\java\util\zip\ZipInputStream.js
call loadScript j2s\java\io\OutputStreamWriter.js
call loadScript j2s\java\util\regex\Pattern.js
call loadScript j2s\java\util\regex\Matcher.js
call loadScript j2s\java\util\regex\MatchResult.js
call loadScript j2s\java\util\Calendar.js
call loadScript j2s\java\io\ByteArrayOutputStream.js
call loadScript j2s\java\io\FileInputStream.js
call loadScript j2s\java\io\FileOutputStream.js
call loadScript j2s\java\io\InputStreamReader.js
call loadScript j2s\java\text\DateFormat.js
call loadScript j2s\java\util\zip\CRC32.js
call loadScript j2s\java\util\zip\ZipEntry.js
call loadScript j2s\java\io\OutputStreamWriter.js
call loadScript j2s\java\util\zip\ZipOutputStream.js
call loadScript j2s\java\io\InputStreamReader.js
call loadScript j2s\java\text\DateFormat.js
call loadScript j2s\java\util\zip\CRC32.js
call loadScript j2s\java\util\zip\ZipEntry.js
call loadScript j2s\java\util\concurrent\Executors.js
call loadScript j2s\java\util\zip\ZipOutputStream.js
call loadScript j2s\java\util\concurrent\Executors.js
